///////////////////////////////////////////////////////////////
//
//   commonConstants.H
//   -----------------
//
//   ECC / IASS
//   Copyright (C) 2020 Edward C. Chan
//
//   LICENSING
//
//   This source code is licensed under the terms of
//   the GNU General Public License as published by
//   the Free Software Foundation, either version 3 for
//   the License or, at your option, any later version.
//
//   DESCRIPTION
//
//   Global variables 
//
///////////////////////////////////////////////////////////////

#ifndef __COMMONCONSTANTS_H__
#define __COMMONCONSTANTS_H__

#include "fvCFD.H"

const scalar BIGG = 1.0e+20;
const scalar TINY = 1.0e-20;

const scalar D2R = M_PI / 180.0;	// degree-radian conversion
const scalar R2D = 180.0 / M_PI;

#endif

				///////////////////////////////////////////////
